INSERT INTO business_departments (department_id, department)
VALUES (001, "Brewing"),
       (002, "Engineering"),
       (003, "Fermentation"),
       (004, "Human Resources"),
       (005, "Innovation"),
       (006, "IT"),
       (007, "Lab"),
       (008, "Logistics"),
       (009, "Maintenance"),
       (010, "Management")
       (011, "Packaging"),
       (012, "Sales"),
       (013, "Sustainability"); 

INSERT INTO employees (employee_id, first_name, last_name, department, roles, title, salary, manager)
VALUES (0001, "Chris", "Fitzgerald", "Brewing", "Brewer", "80000", "Rik Delinger"),
       (0002, "Tom", "Bohs", "Brewing", "Brewer", "80000", "Rik Delinger"),
       (0003, "Rik", "Delinger", "Brewing", "Brewing Manager", "100000", "null"),
       (0004, "Jake", "Mahoney", "Brewing", "Brewer", "80000", "Rik Delinger"),
       (0005, "Mike", "Strazdas", "Engineering"),
       (0006, "Chris", "Donalds", "Engineering"),
       (0007, "Nathan", "Schroder", "Engineering"),
       (0008, "Andrew", "Koehring", "Engineering"),
       (0009, "Mike", "Alsup", "Innovation"),
       (0010, "Pat", "Tkaz", "Innovation"), 
       (0011, "Louwrens", "Wildschut", "Innovation"),
       (0012, "Michael", "Pete", "Innovation"),
       (0013, "Todd", "Cadwell", "Fermentation"),
       (0014, "Jim", "Ammos", "Fermentation"),
       (0015, "Jim", "Dunnham", "Fermentation"),
       (0016, "Stephen", "Kimble", "Fermentation"),
       (0017, "Carrie", "Overton", "Human Resources"),
       (0018, "Mike", "Fuerst", "Human Resources"),
       (0019, "Brendan", "Whimes", "Human Resources"),
       (0020, "Emily", "Palik", "Human Resources"),
       (0021, "Patt", "Rolf", "IT"),
       (0022, "Mike", "Medendorp", "IT"),
       (0023, "Kaleb", "Schumaker", "IT"),
       (0024, "Eric", "Fisher", "IT"),
       (0025, "Jeff", "Mier", "Lab"),
       (0026, "Lorez", "Torrez", "Lab"),
       (0027, "Wade", "Begrow", "Lab"),
       (0028, "Elliot", "Parcell", "Lab"),
       (0029, "Mike", "Simon", "Logistics"),
       (0030, "Kenyatta", "Mayfield", "Logistics"),
       (0031, "David", "Zapanta", "Logistics"),
       (0032, "Kelly", "Ward", "Logistics"),
       (0033, "Dan", "Houston", "Maintenance"),
       (0034, "Sid", "Carrizales", "Maintenance"),
       (0035, "Doug", "Spencer", "Maintenance"),
       (0036, "David", "West", "Maintenance"),
       (0037, "John", "Mallet", "Management"),
       (0038, "Tim", "Gossack", "Management"),
       (0039, "Alex", "Kettles", "Management"),
       (0040, "Andy", "Farrel", "Management"),
       (0041, "Tina", "Anderson", "Sales"),
       (0042, "David", "Munro", "Sales"),
       (0043, "Victoria", "Saunders", "Sales"),
       (0044, "Mike", "Hamel", "Sales"),
       (0045, "Ben", "Duffy", "Packaging"),
       (0046, "Tim", "Lozen", "Packaging"),
       (0047, "Perry", "Dickerson", "Packaging"),
       (0048, "Anothony", "White", "Packaging"),
       (0049, "Walker", "Modic", "Sustainability"),
       (0050, "Kate", "Binder", "Sustainability"),
       (0051, "Willow", "khon", "Sustainability"),
       (0052, "Megan", "Kaiser", "sustainability");